---

- hosts: "{{ server }}"
  remote_user: root
  gather_facts: no
  vars_files:
    - "vars/common.yml"

  tasks:
  - name: fetch data
    fetch:
      src: "{{ pkg }}"
      dest: "{{ dst }}"
      flat: yes
