---

- hosts: "{{ machines }}"
  remote_user: root
  gather_facts: no
  vars_files:
    - "vars/common.yml"

  tasks:
  - name: fetch backup file
    fetch:
      src: "{{ src }}"
      dest: "{{ dst }}"
      flat: yes
