package main

import (
	"encoding/xml"
	"os"
	xml2 "parser/xml"
	"path"
)

type msgs struct {
	XMLName xml.Name `xml:"msgs"`
	Msgs    []msg    `xml:"msg"`
}

type msg struct {
	XMLName xml.Name `xml:"msg"`
	Name    string   `xml:"name,attr"`
	Code    string   `xml:"code,attr"`
	Type    int      `xml:"type,attr"`
	Chan    int      `xml:"chan,attr"`
	Desc    string   `xml:"desc,attr"`
}

var tplMsgNoErl = `%% Automatically generated, do not edit
%% Generated by parse_msgno.go

-ifndef(MSGNO_HRL).
-define(MSGNO_HRL, true).
{{ range .Msgs }}
-define({{ .Name }}, {{ .Code }}). %% {{ .Desc }}
{{ end }}
-endif.
`

func main() {
	x := xml2.ParseXML(os.Args[1], &msgs{})

	if xml2.IsDirExist(os.Args[2]) {
		x.Exec(tplMsgNoErl, nil)
		x.Write(path.Join(os.Args[2], "include", "msgno.hrl"))
		x.Clear()
	}
}
