---

- name: create server path
  file:
    path: "{{ serv_path }}"
    state: directory
    owner: root
    group: root

- name: deploy server
  unarchive:
    creates: "{{ serv_path }}/etc/sys.config"
    remote_src: yes
    src: "{{ pkg }}"
    dest: "{{ serv_path }}"
    owner: root
    group: root
    mode: 0744
