---

- hosts: "{{ machines }}"
  remote_user: root
  gather_facts: no
  vars_files:
    - "vars/common.yml"

  tasks:

  - name: configure ssh
    vars:
        ansible_ssh_port: 22
        ansible_ssh_user: root
        ansible_ssh_pass: "{{ ssh_pass }}"
    block:
    - name: modify sshd config
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        backup: yes
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - regexp: "^#Port 22"
          line: "Port 9922"
        # - regexp: "^PasswordAuthentication"
        #   line: "PasswordAuthentication no"
        # - regexp: "^GSSAPIAuthentication"
        #   line: "GSSAPIAuthentication no"

    - name: add ssh auth key
      copy:
        src: ../installation/authorized_keys
        dest: /root/.ssh/
        mode: 0600

    - name: restart sshd
      service:
        name: sshd
        state: restarted

  - name: create data device
    block:
    - name: part disk
      parted:
        device: /dev/vdb
        number: 1
        state: present
    - name: create filesystem
      filesystem:
        dev: /dev/vdb1
        fstype: ext4
    - name: mount data device
      mount:
        src: /dev/vdb1
        path: /data
        fstype: ext4
        state: mounted

  - name: install dependencies
    yum:
      name:
        - openssl-devel
        - automake
        - autoconf
        - ncurses-devel
        - gcc
        - lrzsz
        - ntpdate
      state: present

  - name: sync server time
    cron:
      name: "sync server time"
      minute: "5"
      job: "/usr/sbin/ntpdate 0.cn.pool.ntp.org"

  - name: install erlang
    block:
      - name: create erlang location
        file:
          path: "{{ erlang_location }}"
          state: directory
          mode: 0755

      - name: unpack source code
        unarchive:
          src: ../installation/otp_src_{{ erlang_version }}.tar.gz
          dest: /root
          owner: root
          group: root
          mode: 0755

      - name: configure installation
        shell: ./configure --without-javac --with-ssl=/usr/bin/ --prefix={{ erlang_location }}
        args:
          chdir: otp_src_{{ erlang_version }}

      - name: make
        make:
          chdir: otp_src_{{ erlang_version }}
          target: all

      - name: install
        make:
          chdir: otp_src_{{ erlang_version }}
          target: install

      - name: create symlink
        file:
          src: "{{ erlang_location }}/bin/erl"
          dest: /usr/local/bin/erl
          owner: root
          group: root
          state: link

  - name: configure system
    copy:
      src: ../installation/bash_alias.sh
      dest: /etc/profile.d
      mode: 0644
  - name: set timezone to {{ timezone }}
    timezone:
      name: "{{ timezone }}"